spring:
  application:
    name: Td-Light-Telegram
  datasource:
    username:
telegram :
  api-id: 34701940
  api-hash: e7ed4d55e0bccab37b69c02eb6c7ca9f

  session-path: tdlight-session
  database-path: tdlight-data
  downloads-path: tdlight-downloads

logging:
  level:

    com.example.tdlighttelegram: DEBUG

    it.tdlight: INFO

    org.springframework: INFO

    root: INFO


  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


  file:
    name: logs/tdlight-pro.log
    max-size: 10MB
    max-history: 30